### ISSUE TITLE
Add other currencies

### ISSUE THREAD

**Issue by nitorrep** [belaczek/hodlwatch#16]
Could it be possible to add other currencies (CHF) ?
And do you plan to add the possibility to add manually some positions?
I found your tools perfect but I'm missing this 2 features !

**Comment by belaczek** [comment]
Hi, I have just added support for CHF. Feel free to check it out.
Manual positions will require more work to get done, but I might look into that.

**Comment by nitorrep** [comment]
Thank you it's cool !
