### ISSUE TITLE
Issue to connect with Binance

### ISSUE THREAD

**Issue by dederaditya** [belaczek/hodlwatch#17]
Hello there,

I tried to deploy the script on my virtual server, and I can't find it's working for Binance. Keep showing me this error
`Error while trying to connect to exchange. Please check your credentials and try again.`
I created an api to read only, and use proxy server but still the same, any idea?

**Comment by belaczek** [comment]
Hi, I have just updated the ccxt library providing access to all the APIs. Can you please check, if that solved your issue?

**Comment by dederaditya** [comment]
> Hi, I have just updated the ccxt library providing access to all the APIs. Can you please check, if that solved your issue?

I will?

**Comment by dederaditya** [comment]
It is working! Thank you so much :)
