### ISSUE TITLE
Source code for the proxy server for transparency

### ISSUE THREAD

**Issue by marcellodesales** [belaczek/hodlwatch#19]
I started using your website, but I can't see the source-code of the proxy server for CORS. 

* Where can I find it?
* Could you provide it in a folder of this project so anyone can reuse it?

thank you
Marcello

**Comment by belaczek** [comment]
Hi, here's the source code for the proxy server. https://github.com/belaczek/cors-anywhere

**Comment by marcellodesales** [comment]
Thank you!
