### ISSUE TITLE
Where can I find your proxy code?

### ISSUE THREAD

**Issue by Aurelyn10** [belaczek/hodlwatch#7]
I would like to confirm the code for this proxy.
https://hodlwatch-proxy.herokuapp.com/
thanks

**Comment by belaczek** [comment]
Hi, sorry for late answer. It is this one https://github.com/belaczek/cors-anywhere. Feel free to deploy your own instance.

**Comment by Aurelyn10** [comment]
How to run the app successfully and safely?
I run the app using `npm run test` But it is not working even in both cases, using proxy or not.
"Error while trying to connect to exchange. Please check your credentials and try again."
credentials are correct.

**Comment by belaczek** [comment]
If I understand it correctly, you want to run both the app and cors server locally. To do so you have to first start the cors server, which will be in default running on `0.0.0.0:8080`. To access it from within the app (running also locally), use `http://localhost:8080/` as proxy url (including the last `/` slash). 
Let me know if that helps.

**Comment by Aurelyn10** [comment]
Yes It is working.
Thank you.
