### ISSUE TITLE
Instructions Startup

### ISSUE THREAD

**Issue by DanielXYZ2000** [belaczek/hodlwatch#8]
Hi,
Could you add how to start this local on the PC.
What are the requirements (installed tools, settings)?
Which steps to open the webpage?
This could be helpful for beginner
Thx

**Comment by BugHunterPhilosopher** [comment]
Thanks for this software! But I am unable to launch it, too. Can you please provide info? It looks so great... :-)

I use: yarn serve dist
And get a 404 on http://localhost:5000 & http://localhost:5000/app

**Comment by belaczek** [comment]
Hi, thanks for the feedback and sorry for late response. I have added `How to run locally` section into Readme. 
Let me know if you encounter any other issues.

**Comment by BugHunterPhilosopher** [comment]
Thank you very much, it works now!
